//int totalMoney = 50;
//int totalDrinked = 0;
//int exchangedQty = 2;
//int onHandBottles = 0;
import com.codemonkey.drools.BottleProblem;

rule "buy"
	when
		bp : BottleProblem(totalMoney > 0)
	then
		bp.totalMoney -= 1;
		bp.totalDrinked += 1;
		bp.onHandBottles += 1;
		System.out.println( " buy one bottle and drinked , money left = " + bp.totalMoney + " "); 
		update( bp );
end

rule "return 2 empty bottle and get new one then drinked"
	when
		bp : BottleProblem(onHandBottles >= exchangedQty)
	then
		System.out.println( "return 2 empty bottle and get new one then drinked" ); 
		bp.totalDrinked += 1;
		bp.onHandBottles = bp.onHandBottles - 2 + 1;
		update( bp );
end